server:
  port: 8080

management:
  endpoint.gateway.enabled: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: refresh
          uri: lb://authentication
          predicates:
            Path=/auth/refresh
          filters:
            - AuthFilter
        - id: sign-in
          uri: lb://authentication
          predicates:
            Path=/auth/signin
        - id: sign-in
          uri: lb://authentication
          predicates:
            Path=/auth/signout
        - id: sign-in
          uri: lb://authentication
          predicates:
            Path=/auth/signup

        - id: user
          uri: lb://authentication
          predicates:
            Path=/user/**
          filters:
            - AuthFilter
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true